kind: Job
apiVersion: batch/v1
metadata:
  name: medseg3001
spec:
  template:
    spec:
      containers:
      - name: medseg
        image: "halyjo/medseg:v1"
        workingDir: /storage/experiments/
        command: ["sh", "MedSeg.sh"]
        stdin: true
        tty: true
        env: 
        - name: "WANDB_API_KEY"
          value: c5322a72504a88ce9a6a4e0711250af4efd42604
        volumeMounts:
        - name: storage
          mountPath: /storage
      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: storage
      restartPolicy: OnFailure
  backoffLimit: 0
